language: node_js
node_js:
  -  8.4.0
cache:
  directories:
    - "node_modules"
env:
  - NODE_ENV=test
services:
  - postgresql

before_script:
  - npm run setup:config
  - psql -U postgres -c "CREATE DATABASE sample_test"
  - psql -U postgres -c "CREATE USER sample WITH PASSWORD 'password'"
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE sample_test TO sample;"
  - psql -U postgres -c "CREATE EXTENSION citext;"
  - npm run dbmigrate:up
addons:
  postgresql: "9.4"

  