language: node_js
node_js:
  -  8.4.0
cache:
  directories:
    - "node_modules"

services:
  - postgresql

before_script:
  - npm run setup:config
  - psql -c 'create database sample;' -U postgres