language: node_js
node_js:
  -  8.4.0
cache:
  directories:
    - "node_modules"
env:
  - NODE_ENV=test
services:
  - postgresql

before_script:
  - npm run setup:config
  - psql -U root -c "CREATE DATABASE sample-test"
  - psql -U root -c "CREATE USER sample WITH PASSWORD 'password'"
  - psql -U root -c "GRANT ALL PRIVILEGES ON DATABASE 'sample-test' TO sample;"
addons:
  postgresql: "9.4"