language: node_js
node_js:
  -  8.4.0
cache:
  directories:
    - "node_modules"
env:
  - NODE_ENV=test
services:
  - postgresql

before_script: 
  - npm run setup:config
  - ./src/scripts/before.travis.script.sh
addons:
  postgresql: "9.4"

  