version: "2"
networks:
  myapp:

services:
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      myapp:
        aliases:
          - postgres
  web:
    build: .
    command: npm start
    ports:
      - "80:4000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
    networks:
      myapp:
        aliases:
          - web
